# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-FTP-Common
version:      6.1
version_from: lib/Net/FTP/Common.pm
installdirs:  site
requires:
    Net::FTP:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
